name: Check Release
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JupyterLab (includes jlpm)
        run: pip install jupyterlab

      - name: Install JS deps
        run: jlpm install --frozen-lockfile

      - name: Build JS package
        run: jlpm build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install jupyter-releaser
        run: pip install jupyter-releaser
      - name: Check Release
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Distributions
        uses: actions/upload-artifact@v4
        with:
          name: jupyterlab_docs_helper-releaser-dist-${{ github.run_number }}
          path: .jupyter_releaser_checkout/dist
