name: Protect main branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  administration: write

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce branch protection
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const params = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: false,
                checks: []
              },
              enforce_admins: true,
              required_pull_request_reviews: null,
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_linear_history: true,
              lock_branch: false
            };

            await github.request('PUT /repos/{owner}/{repo}/branches/{branch}/protection', params);
